Orthotropic material preparation
Virtonomy/SPHinXsys pull request #36
Opened 2021-09-23 09:44 UTC by BenceVirtonomy

2021-10-03 18:16 UTC, BenceVirtonomy commented on SPHINXsys/src/shared/materials/elastic_solid.cpp
> +		G_[0]=2/(Mu_[0]+Mu_[1]);
G is input and we need to get all the Mu

2021-10-03 18:18 UTC, BenceVirtonomy commented on SPHINXsys/src/shared/materials/elastic_solid.h
> +		OrthotropicSolid(Real rho_0, std::array<Vecd, 3> a, std::array<Real, 3> E, std::array<Real, 3> G,std::array<Real, 3> poisson)
we have to call all these functions in the constructor here:
CalculateAllMu();
CalculateAllLambda();
CalculateA0();

2021-10-03 18:21 UTC, BenceVirtonomy commented on SPHINXsys/src/shared/materials/elastic_solid.cpp
> +		Matd Complience= Matd(Vecd(1/E_[1], -poisson_[1]/E_[1], -poisson_[2]/E_[1]),
please put comments and explain the indeces: possions[1] means nu_12 etc.

2021-10-03 18:23 UTC, BenceVirtonomy commented on SPHINXsys/src/shared/materials/elastic_solid.cpp
> +		Lambda_[0]=Compliance_inv[0][0]-2*Mu_[0];
same here, explain which Lambda is which

2021-10-03 18:23 UTC, BenceVirtonomy commented on SPHINXsys/src/shared/materials/elastic_solid.cpp
> +		Lambda_[2]=Compliance_inv[1][1]-2*Mu_[2];
should be Compliance_inv[2][2]

2021-10-03 18:24 UTC, BenceVirtonomy commented on SPHINXsys/src/shared/materials/elastic_solid.h
> +		OrthotropicSolid(Real rho_0, std::array<Vecd, 3> a, std::array<Real, 3> E, std::array<Real, 3> G,std::array<Real, 3> poisson)
and we should also move the constructor to the .cpp and only declare it here

2021-10-03 18:25 UTC, BenceVirtonomy commented on SPHINXsys/src/shared/materials/elastic_solid.h
> +		//Vecd f0_, s0_; 				/**< Reference fiber and sheet directions as basic parameter. */
delete these, that we don't need

2021-10-03 18:26 UTC, BenceVirtonomy commented on SPHINXsys/src/shared/materials/elastic_solid.h
> +		Real Lambda_[6]; //123-main 456-side
explain the indices a bit more detailed

2021-10-13 17:43 UTC, EttoTor commented on SPHINXsys/src/shared/materials/elastic_solid.h
>  		OrthotropicSolid() : LinearElasticSolid()
https://help.febio.org/FEBio/FEBio_tm_2_7/FEBio_tm_2-7-Subsection-5.2.2.html#prev

2021-10-24 17:10 UTC, chuvirtonomy requested changes

2021-10-24 17:10 UTC, chuvirtonomy commented on SPHINXsys/src/shared/common/small_vectors.cpp
> +	Real CalculateDoubleDotProduct(Mat2d Matrix1, Mat2d Matrix2 )
this function looks problematic for me. how do you know the size of the matrix is (2,2)? can not be larger than 2x2?

2021-10-24 17:10 UTC, chuvirtonomy commented on SPHINXsys/src/shared/common/small_vectors.cpp
> +	Real CalculateDoubleDotProduct(Mat3d Matrix1, Mat3d Matrix2 )
This is also strange for me. It does not seems to be you are doing dot product.

2021-10-24 22:36 UTC, chuvirtonomy approved these changes

2021-10-26 12:50 UTC, merged