new runtime vtuString simulation func
Virtonomy/SPHinXsys pull request #48
Opened 2021-10-19 17:48 UTC by mrezavandVirtonomy

new runtime vtuString I/O function is written to write VTUs in run time using a std::pair

2021-10-19 17:54 UTC, chuvirtonomy requested changes

2021-10-19 17:54 UTC, chuvirtonomy commented on SPHINXsys/src/shared/io_system/in_output.h
> +		virtual void writeWithFileName(const std::string& sequence) override;
I think you dont need virtual keyword since this function is already override the original virtual function

2021-10-19 18:08 UTC, chuvirtonomy approved these changes

2021-10-19 18:08 UTC, mrezavandVirtonomy commented on SPHINXsys/src/shared/io_system/in_output.h
> +		virtual void writeWithFileName(const std::string& sequence) override;
Right. I removed it.

2021-10-20 11:17 UTC, BenceVirtonomy approved these changes

2021-10-22 07:33 UTC, merged